name: Matrix Demo

on:
  pull_request:
    branches:
      - main

jobs:
  example_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [10, 12, 14]
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Show matrix combination
        run: echo ${{ matrix.version }}-${{ matrix.os }}
        if: ${{ matrix.version == 10 }}
